defaults:
  - _self_

#agent_name: svea

agent:
  _target_: methods.PPO.PPO
  ppo_epoch: 2
  clip_param: 0.1
  use_clipped_value_loss: true
  value_loss_coef: 0.1
  entropy_coef: 0.01
  max_grad_norm: 0.5
  uav_net_cfg:
    uav_loc_obs_channel_num: ${uav_loc_obs_channel_num}
    lr: ${lr}
    eps: ${eps}
    hidden_size: ${hidden_size}
